version: "3.7"

services:
  currency-logging-service:
    image: openzipkin/zipkin:latest
    depends_on:
      - rabbitmq
    expose:
      - 9411
    ports:
      - "9411:9411"
    networks:
      - currency-network
    environment:
      - RABBIT_ADDRESSES=rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - currency-network

  currency-naming-service:
    image: mssm1996/currency-naming-service:0.0.1-SNAPSHOT
    ports:
      - "8761:8761"
    depends_on:
      - currency-logging-service
    networks:
      - currency-network

  currency-exchange-service:
    image: mssm1996/currency-exchange-service:0.0.1-SNAPSHOT
    depends_on:
      - currency-naming-service
    ports:
      - "8000:8000"
    networks:
      - currency-network
    environment:
      eureka.client.service-url.defaultZone: "http://currency-naming-service:8761/eureka"
      spring.zipkin.sender.type: rabbit
      spring.rabbitmq.host: rabbitmq
      spring.rabbitmq.port: 5672

  currency-conversion-service:
    image: mssm1996/currency-conversion-service:0.0.1-SNAPSHOT
    depends_on:
      - currency-exchange-service
    ports:
      - "8100:8100"
    networks:
      - currency-network
    environment:
      eureka.client.service-url.defaultZone: "http://currency-naming-service:8761/eureka"
      spring.zipkin.sender.type: rabbit
      spring.rabbitmq.host: rabbitmq
      spring.rabbitmq.port: 5672

  currency-gateway-service:
    image: mssm1996/currency-gateway-service:0.0.1-SNAPSHOT
    depends_on:
      - currency-exchange-service
      - currency-conversion-service
    ports:
      - "8765:8765"
    networks:
      - currency-network
    environment:
      eureka.client.service-url.defaultZone: "http://currency-naming-service:8761/eureka"
      spring.zipkin.sender.type: rabbit
      spring.rabbitmq.host: rabbitmq
      spring.rabbitmq.port: 5672

networks:
  currency-network: